# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  -
    # Name template of the recipe
    # Default to project name
    name: myproject
    tap:
      owner: wsharp07
      name: homebrew-multitool
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    homepage: "https://github.com/wsharp07/multitool-cli"
    description: "A cool thing"
    test: |
      system "#{bin}/multitool-cli version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
